### ISSUE TITLE
Akka 2.5 compatibility 

### ISSUE THREAD

**Issue by stikkos** [kamon-io/kamon-datadog#11]
Currently, the datadog integration does not work with Akka 2.5 (and Kamon 1.0).
Any idea when this will be supported?
Anything I can do to help?

**Comment by ivantopo** [comment]
Hey @stikkos, we [published a snapshot version](https://gitter.im/kamon-io/Kamon?at=5a79b78236de78850cfaa150) for Kamon 1.0, there is only one thing missing which would be moving away form the Async HTTP client, I'll try to do that soon and release an RC version for the module, please give it a try and let us know if you find any issues.

**Comment by ivantopo** [comment]
Oh and btw, Kamon doesn't use Akka at all anymore so, no compatibility issues :)
