### ISSUE TITLE
Kamon 1.x version 

### ISSUE THREAD

**Issue by jmaynier** [kamon-io/kamon-datadog#14]
When do you think a kamon-datadog release compatible with kamon verions 1.x wil be released ?
Does the kamon-datadog 1.0 branch is stable enough for production ?

**Comment by nilsga** [comment]
Any news regarding 1.x compatibility? What are the remaining issues to be resolved?

**Comment by captainmannering** [comment]
I am also wondering about this, a 1.x compatible version would be great.

**Comment by jasonmartens** [comment]
Hello @ivantopo, looks like you have work underway in the `kamon-1.0` branch for a 1.0 release. I'm interested in assisting with that task if there is anything I can do.

**Comment by izakp** [comment]
@ivantopo looking for this functionality as well - please update here when https://github.com/kamon-io/kamon-datadog/pull/16 is closed and/or a `1.0` release is out

**Comment by dominics** [comment]
Looks like this is done and can be closed
