### ISSUE TITLE
Cannot report tracing

### ISSUE THREAD

**Issue by eugenemiretsky** [kamon-io/kamon-datadog#30]
I am reporting tracing using Kamon as per the [doc](https://kamon.io/docs/latest/core/tracing/), and have enabled apm in the datadog agent, but I cannot find any in trace/service list in Datadog. What am I missing? Does the integration work?

**Comment by eugenemiretsky** [comment]
I have looked at the code, and I cannot find 8126 (the port Datadog expect tacing on) anywhere, which leads me to believe that the datadog agent doesn't report tracing?

**Comment by eugenemiretsky** [comment]
After looking at the code I can confirm that Tracing is not supported - may want to add this to the doc

**Comment by dpsoft** [comment]
Hey @eugenemiretsky please take a look: https://github.com/kamon-io/kamon-datadog/pull/29
