### ISSUE TITLE
The latest version 0.6.7 is not compatible with scala 2.12

### ISSUE THREAD

**Issue by ufosky** [kamon-io/kamon-datadog#4]
The latest version 0.6.7 has a dependence `scala-java8-compat` without package for scala 2.12, its latest version is 0.8.0.

```
"org.scala-lang.modules" %% "scala-java8-compat"  % "0.5.0"
```

**Comment by dpsoft** [comment]
@ufosky thanks for reporting this issue, I just published the `0.6.8`.
