### ISSUE TITLE
kamon-datadog 0.6.5 depends on different akka-http between 2.11 and 2.12

### ISSUE THREAD

**Issue by blast-hardcheese** [kamon-io/kamon-datadog#6]
I'm currently stuck in a situation where I can't upgrade akka-http to 10.0.x on scala 2.11 due to the dependency conflict in kamon-datadog. Other servers using 2.12 don't experience this, which is surprising.

Releasing more frequently and consistently across the different supported scala versions (to give a grace period for upgrading from akka 2.3.x to 2.4.x in 2.10 or 2.11, instead of forcing upgrading everything at once, which is our current scenario)

Depending on different versions between scala versions is significantly bad form; scala itself focuses on source-compatibility across releases, not binary-compatibility, so not following this puts you at odds with the expected versioning strategy in the community.

Thank you for your consideration

**Comment by unoexperto** [comment]
What issue are you having exactly? I have multiproject app. I'm on Scala 2.11.11 and Akka-http 10.0.10 with latest kamon.

**Comment by blast-hardcheese** [comment]
@unoexperto The issue is that different releases for various supported scala ABI should be consistent -- I have two projects, one is scala 2.11, the other 2.12. Unfortunately, these are legacy projects that are still using maven, and in this case, maven evicted the newer versions of akka in favor of 2.3.x. I can manually exclude akka 2.3.x being brought in by kamon-datadog, but then I have no guarantees that kamon-datadog won't blow up with `ClassNotFound`s any time I upgrade.

The question of upgrading kamon projects to newer versions of akka/akka-http aside, I'd still like to understand why the exact same version of kamon-datadog depends on different akka versions depending on which version of scala it's built for.

**Comment by ivantopo** [comment]
Just for the record, these issues were resolved long ago!
